<a href="https://colab.research.google.com/github/rohith-rr/deep-learning-projects/blob/main/Gradient_descent.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Implement Gradient Descent For Neural Network (or Logistic Regression)
Predicting if a person would buy life insurnace based on his age using logistic regression
Above is a binary logistic regression problem as there are only two possible outcomes (i.e. if person buys insurance or he/she doesn't).

In [1]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
import pandas as pd
from matplotlib import pyplot as plt
%matplotlib inline

In [2]:
df=pd.read_csv("/content/insurance_data.csv")
df.head()

age  affordibility  bought_insurance
0   22              1                 0
1   25              0                 0
2   47              1                 1
3   52              0                 0
4   46              1                 1

In [19]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df[['age','affordibility']],df.bought_insurance,test_size=0.2,random_state=25)

In [8]:
len(X_train)

22

In [12]:
X_train_scaled = X_train.copy()
X_train_scaled['age'] = X_train_scaled['age'] / 100
X_test_scaled = X_test.copy()
X_test_scaled['age'] = X_test_scaled['age'] / 100

In [14]:
X_train_scaled

age  affordibility
0   0.22              1
13  0.29              0
6   0.55              0
17  0.58              1
24  0.50              1
19  0.18              1
25  0.54              1
16  0.25              0
20  0.21              1
3   0.52              0
7   0.60              0
1   0.25              0
5   0.56              1
27  0.46              1
8   0.62              1
18  0.19              0
12  0.27              0
23  0.45              1
22  0.40              1
15  0.55              1
26  0.23              1
4   0.46              1

In [20]:
model=keras.Sequential([keras.layers.Dense(1,input_shape=(2,),activation='sigmoid',kernel_initializer='ones',bias_initializer='zeros')])
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
model.fit(X_train_scaled,y_train,epochs=6000)

Streaming output truncated to the last 5000 lines.
1/1 [==============================] - 0s 11ms/step - loss: 0.4985 - accuracy: 0.9091
Epoch 3502/6000
1/1 [==============================] - 0s 11ms/step - loss: 0.4984 - accuracy: 0.9091
Epoch 3503/6000
1/1 [==============================] - 0s 11ms/step - loss: 0.4984 - accuracy: 0.9091
Epoch 3504/6000
1/1 [==============================] - 0s 10ms/step - loss: 0.4984 - accuracy: 0.9091
Epoch 3505/6000
1/1 [==============================] - 0s 11ms/step - loss: 0.4984 - accuracy: 0.9091
Epoch 3506/6000
1/1 [==============================] - 0s 9ms/step - loss: 0.4983 - accuracy: 0.9091
Epoch 3507/6000
1/1 [==============================] - 0s 11ms/step - loss: 0.4983 - accuracy: 0.9091
Epoch 3508/6000
1/1 [==============================] - 0s 10ms/step - loss: 0.4983 - accuracy: 0.9091
Epoch 3509/6000
1/1 [==============================] - 0s 10ms/step - loss: 0.4982 - accuracy: 0.9091
Epoch 3510/6000
1/1 [===========================

In [21]:
model.evaluate(X_test_scaled,y_test)

1/1 [==============================] - 0s 141ms/step - loss: 0.3185 - accuracy: 1.0000


[0.318513423204422, 1.0]

In [22]:
model.predict(X_test_scaled)

1/1 [==============================] - 0s 72ms/step


array([[0.7182663 ],
       [0.31143513],
       [0.1407243 ],
       [0.45088157],
       [0.74176073],
       [0.85454607]], dtype=float32)

In [24]:
def sigmoid(x):
  import math
  return 1/(1+math.exp(-x))
sigmoid(18)

0.9999999847700205

In [29]:
coef,intercept=model.get_weights()


In [26]:
def prediction_function(age,affordibility):
  weighted_sum=coef[0]*age+coef[1]*affordibility+intercept
  return sigmoid(weighted_sum)

In [30]:
prediction_function(0.47,1)

0.7182662889302092

In [31]:
def log_loss(y_true,y_predicted):
  epsilon=1e-15
  y_predicted_new=[max(1,epsilon) for i in y_predicted]
  y_predicted_new=[min(i,1-epsilon) for i in y_predicted_new]
  y_predicted_new=np.array(y_predicted_new)
  return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [36]:
def sigmoid_numpy(x):
  return 1/(1+np.exp(-x))

siogmoid_numpy(np.array([12,0,1]))

array([0.99999386, 0.5       , 0.73105858])

In [35]:
def gradient_descent(age, affordability, y_true, epochs, loss_thresold):
    w1 = w2 = 1
    bias = 0
    rate = 0.5
    n = len(age)
    for i in range(epochs):
        weighted_sum = w1 * age + w2 * affordability + bias
        y_predicted = sigmoid_numpy(weighted_sum)
        loss = log_loss(y_true, y_predicted)

        w1d = (1/n)*np.dot(np.transpose(age),(y_predicted-y_true))
        w2d = (1/n)*np.dot(np.transpose(affordability),(y_predicted-y_true))

        bias_d = np.mean(y_predicted-y_true)
        w1 = w1 - rate * w1d
        w2 = w2 - rate * w2d
        bias = bias - rate * bias_d

        print (f'Epoch:{i}, w1:{w1}, w2:{w2}, bias:{bias}, loss:{loss}')

        if loss<=loss_thresold:
            break

    return w1, w2, bias

In [37]:
gradient_descent(X_train_scaled['age'],X_train_scaled['affordibility'],y_train,1000, 0.4631)

Epoch:0, w1:0.974907633470177, w2:0.948348125394529, bias:-0.11341867736368583, loss:17.26978799617044
Epoch:1, w1:0.9556229728273669, w2:0.9058873696677865, bias:-0.2122349122718517, loss:17.26978799617044
Epoch:2, w1:0.9416488476693794, w2:0.8719790823960313, bias:-0.2977578997796538, loss:17.26978799617044
Epoch:3, w1:0.9323916996249162, w2:0.8457541517722915, bias:-0.3715094724003511, loss:17.26978799617044
Epoch:4, w1:0.9272267472726993, w2:0.8262362885332687, bias:-0.43506643026891584, loss:17.26978799617044
Epoch:5, w1:0.9255469396815343, w2:0.8124402814952774, bias:-0.48994490058938817, loss:17.26978799617044
Epoch:6, w1:0.9267936114129968, w2:0.8034375029757677, bias:-0.5375299543522853, loss:17.26978799617044
Epoch:7, w1:0.93047170420295, w2:0.7983920007454487, bias:-0.5790424270894963, loss:17.26978799617044
Epoch:8, w1:0.9361540784567942, w2:0.7965748796787705, bias:-0.6155315088627655, loss:17.26978799617044
Epoch:9, w1:0.9434791243557357, w2:0.7973647616854131, bias:-0.64

(8.270239516056172, 1.6332228396255535, -4.425953608965705)

In [38]:
coef, intercept

(array([[5.963092 ],
        [1.4929159]], dtype=float32),
 array([-3.359691], dtype=float32))